### ISSUE TITLE
Open to add MacOS support?

### ISSUE THREAD

**Issue by tladesignz** [tls-inspector/curl-ios#1]
Hi!

Thank you for this wonderful work!

I'm in the process of putting together a nice wrapper around this library so I can use it in [Envoy for Apple](https://github.com/greatfire/envoy/tree/master/apple).

That lib will also support MacOS.
Of course I can adapt your awesome build scripts and create the MacOS build myself, but it would be way nicer, if I had a single source for both.

How do you feel about offering both at once?

I could provide a PR, if you don't have time for the modifications.

**Comment by ecnepsnai** [comment]
Hi, thanks for the feedback!

I think for now it'd probably be best if you fork this project so you can freely add macOS support.

This repo & script were created pretty much exclusively for TLS Inspector, and since that is an iOS only app (and unlikely to change), I don't want to take on the added maintenance work or concern of breaking macOS support.

Thanks for your understanding and I really look forward to seeing what you do with the script.

**Comment by tladesignz** [comment]
That's a pity for me, but understandable. Thank you!
